# Generated by Django 6.0 on 2025-12-29 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='재설정 토큰', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='토큰 만료 시간')),
                ('is_used', models.BooleanField(default=False, help_text='사용 여부')),
                ('used_at', models.DateTimeField(blank=True, help_text='사용 시간', null=True)),
                ('user', models.ForeignKey(help_text='연결된 사용자', on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '비밀번호 재설정 토큰',
                'verbose_name_plural': '비밀번호 재설정 토큰',
                'db_table': 'password_reset_tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
