# Generated by Django 6.0 on 2025-12-30 02:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def migrate_user_stats_data(apps, schema_editor):
    """기존 User의 게임 통계를 UserStats로 이전"""
    User = apps.get_model('accounts', 'User')
    UserStats = apps.get_model('accounts', 'UserStats')

    for user in User.objects.all():
        UserStats.objects.create(
            user=user,
            rating=getattr(user, 'rating', 1200),
            games_played=getattr(user, 'games_played', 0),
            games_won=getattr(user, 'games_won', 0),
            games_lost=getattr(user, 'games_lost', 0),
            games_draw=getattr(user, 'games_draw', 0),
        )


def reverse_migrate_user_stats_data(apps, schema_editor):
    """롤백 시 UserStats 데이터를 User로 복원 (불가능하므로 pass)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1200, help_text='ELO 레이팅 시스템')),
                ('games_played', models.IntegerField(default=0, help_text='총 게임 수')),
                ('games_won', models.IntegerField(default=0, help_text='승리 수')),
                ('games_lost', models.IntegerField(default=0, help_text='패배 수')),
                ('games_draw', models.IntegerField(default=0, help_text='무승부 수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '사용자 통계',
                'verbose_name_plural': '사용자 통계',
                'db_table': 'user_stats',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': '사용자', 'verbose_name_plural': '사용자'},
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='rating_range',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='games_played_positive',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='가입일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='활성 계정'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='관리자 권한'),
        ),
        migrations.AddField(
            model_name='userstats',
            name='user',
            field=models.OneToOneField(help_text='연결된 사용자', on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(migrate_user_stats_data, reverse_migrate_user_stats_data),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='games_draw',
        ),
        migrations.RemoveField(
            model_name='user',
            name='games_lost',
        ),
        migrations.RemoveField(
            model_name='user',
            name='games_played',
        ),
        migrations.RemoveField(
            model_name='user',
            name='games_won',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddIndex(
            model_name='userstats',
            index=models.Index(fields=['-rating'], name='stats_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='userstats',
            index=models.Index(fields=['-games_played'], name='stats_games_idx'),
        ),
        migrations.AddConstraint(
            model_name='userstats',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 0), ('rating__lte', 4000)), name='stats_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='userstats',
            constraint=models.CheckConstraint(condition=models.Q(('games_played__gte', 0)), name='stats_games_played_positive'),
        ),
        migrations.AddConstraint(
            model_name='userstats',
            constraint=models.CheckConstraint(condition=models.Q(('games_won__gte', 0)), name='stats_games_won_positive'),
        ),
        migrations.AddConstraint(
            model_name='userstats',
            constraint=models.CheckConstraint(condition=models.Q(('games_lost__gte', 0)), name='stats_games_lost_positive'),
        ),
        migrations.AddConstraint(
            model_name='userstats',
            constraint=models.CheckConstraint(condition=models.Q(('games_draw__gte', 0)), name='stats_games_draw_positive'),
        ),
    ]
