# Generated by Django 6.0 on 2025-12-30 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_refactor_user_model_and_add_stats"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="socialuser",
            name="access_token",
        ),
        migrations.RemoveField(
            model_name="socialuser",
            name="refresh_token",
        ),
        migrations.RemoveField(
            model_name="socialuser",
            name="token_expires_at",
        ),
    ]
