# Generated by Django 6.0 on 2025-12-30 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def migrate_existing_users(apps, schema_editor):
    User = apps.get_model("accounts", "User")

    now = timezone.now()
    User.objects.filter(email_verified=False).update(
        email_verified=True, email_verified_at=now
    )


def reverse_migrate(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_social_user_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(default=False, help_text="이메일 인증 완료 여부"),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verified_at",
            field=models.DateTimeField(blank=True, help_text="이메일 인증 완료 시간", null=True),
        ),
        migrations.CreateModel(
            name="EmailVerificationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True, help_text="이메일 인증 토큰", max_length=64, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(help_text="토큰 만료 시간")),
                ("is_used", models.BooleanField(default=False, help_text="사용 여부")),
                ("used_at", models.DateTimeField(blank=True, help_text="사용 시간", null=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="연결된 사용자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_verification_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "이메일 인증 토큰",
                "verbose_name_plural": "이메일 인증 토큰",
                "db_table": "email_verification_tokens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RunPython(migrate_existing_users, reverse_migrate),
    ]
