# Generated by Django 6.0 on 2025-12-31 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_email_verified_user_email_verified_at_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="emailverificationtoken",
            index=models.Index(fields=["user", "is_used"], name="idx_user_is_used"),
        ),
        migrations.AddIndex(
            model_name="emailverificationtoken",
            index=models.Index(fields=["expires_at"], name="idx_expires_at"),
        ),
    ]
