# Generated by Django 6.0 on 2026-01-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_emailverificationtoken_idx_user_is_used_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="scheduled_deletion_at",
            field=models.DateTimeField(
                blank=True, help_text="탈퇴 예정 시간 (이 시간 전에 로그인하면 취소)", null=True
            ),
        ),
    ]
