# Generated by Django 6.0 on 2026-01-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_add_scheduled_deletion_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverificationtoken",
            name="new_email",
            field=models.EmailField(
                blank=True, help_text="이메일 변경 요청 시 새 이메일", max_length=254, null=True
            ),
        ),
    ]
