# Generated by Django 6.0 on 2026-01-12 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_limit_social_user_per_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "token_type",
                    models.CharField(
                        choices=[
                            ("email_verification", "이메일 인증"),
                            ("password_reset", "비밀번호 재설정"),
                        ],
                        help_text="토큰 타입",
                        max_length=20,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True, help_text="인증 토큰", max_length=64, unique=True
                    ),
                ),
                (
                    "new_email",
                    models.EmailField(
                        blank=True,
                        help_text="이메일 변경 요청 시 새 이메일",
                        max_length=254,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(help_text="토큰 만료 시간")),
                ("is_used", models.BooleanField(default=False, help_text="사용 여부")),
                ("used_at", models.DateTimeField(blank=True, help_text="사용 시간", null=True)),
            ],
            options={
                "verbose_name": "인증 토큰",
                "verbose_name_plural": "인증 토큰",
                "db_table": "auth_tokens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveIndex(
            model_name="emailverificationtoken",
            name="idx_user_is_used",
        ),
        migrations.RemoveIndex(
            model_name="emailverificationtoken",
            name="idx_expires_at",
        ),
        migrations.AddField(
            model_name="authtoken",
            name="user",
            field=models.ForeignKey(
                help_text="연결된 사용자",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auth_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="emailverificationtoken",
            name="user",
        ),
        migrations.DeleteModel(
            name="PasswordResetToken",
        ),
        migrations.AddIndex(
            model_name="authtoken",
            index=models.Index(fields=["user", "token_type", "is_used"], name="idx_user_type_used"),
        ),
        migrations.AddIndex(
            model_name="authtoken",
            index=models.Index(fields=["expires_at"], name="idx_token_expires_at"),
        ),
        migrations.DeleteModel(
            name="EmailVerificationToken",
        ),
    ]
