# Generated by Django 6.0 on 2026-01-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_add_auth_token_model"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email_verified"], name="idx_user_email_verified"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["scheduled_deletion_at"], name="idx_user_scheduled_del"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_active", "email_verified"], name="idx_user_active_verified"
            ),
        ),
    ]
