# Generated by Django 6.0 on 2026-01-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_add_user_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="userstats",
            name="stats_rating_idx",
        ),
        migrations.RemoveIndex(
            model_name="userstats",
            name="stats_games_idx",
        ),
        migrations.AddIndex(
            model_name="userstats",
            index=models.Index(fields=["-rating", "-games_played"], name="stats_ranking_idx"),
        ),
    ]
