# Generated by Django 5.x on 2026-01-28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_add_friend_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignupEmailToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", models.EmailField(max_length=254, help_text="인증 대상 이메일")),
                (
                    "token",
                    models.CharField(
                        max_length=64, unique=True, db_index=True, help_text="인증 토큰"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(help_text="토큰 만료 시간")),
                ("is_used", models.BooleanField(default=False, help_text="사용 여부")),
                (
                    "used_at",
                    models.DateTimeField(null=True, blank=True, help_text="사용 시간"),
                ),
            ],
            options={
                "db_table": "signup_email_tokens",
                "ordering": ["-created_at"],
                "verbose_name": "회원가입 이메일 토큰",
                "verbose_name_plural": "회원가입 이메일 토큰",
            },
        ),
        migrations.AddIndex(
            model_name="signupemailtoken",
            index=models.Index(fields=["email", "is_used"], name="idx_signup_email_used"),
        ),
        migrations.AddIndex(
            model_name="signupemailtoken",
            index=models.Index(fields=["expires_at"], name="idx_signup_email_expires"),
        ),
    ]
