# Generated by Django 5.x on 2026-01-28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_add_signup_email_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="signupemailtoken",
            name="code_hash",
            field=models.CharField(default="", max_length=64, help_text="인증 코드 해시"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="signupemailtoken",
            name="attempts",
            field=models.PositiveSmallIntegerField(default=0, help_text="인증 시도 횟수"),
        ),
        migrations.AlterField(
            model_name="signupemailtoken",
            name="token",
            field=models.CharField(
                max_length=64, unique=True, db_index=True, help_text="내부 토큰"
            ),
        ),
    ]
