# Generated by Django 6.0 on 2026-02-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_add_guestbook_and_dm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialuser",
            name="provider",
            field=models.CharField(
                choices=[("kakao", "Kakao"), ("naver", "Naver")],
                help_text="OAuth 제공자",
                max_length=20,
            ),
        ),
    ]
