# Generated by Django 6.0 on 2026-02-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_add_competitive_stats"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuestSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("nickname", models.CharField(max_length=20)),
                ("display_name", models.CharField(max_length=30)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["expires_at"], name="accounts_gu_expires_4de899_idx"),
                    models.Index(fields=["token"], name="accounts_gu_token_efbe29_idx"),
                ],
            },
        ),
    ]
