# Generated by Django 6.0 on 2026-02-19 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_add_guest_session_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestsession",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guest_session",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_guest",
            field=models.BooleanField(default=False, help_text="게스트 임시 계정"),
        ),
    ]
