# Generated by Django 6.0 on 2026-02-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_add_guest_user_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="userstats",
            name="nickname_color",
            field=models.CharField(blank=True, default="", help_text="닉네임 색상 키", max_length=20),
        ),
        migrations.AddField(
            model_name="userstats",
            name="profile_border",
            field=models.CharField(blank=True, default="", help_text="프로필 테두리 키", max_length=20),
        ),
        migrations.AddField(
            model_name="userstats",
            name="style_points",
            field=models.IntegerField(default=0, help_text="커스터마이징 포인트"),
        ),
        migrations.AddConstraint(
            model_name="userstats",
            constraint=models.CheckConstraint(
                condition=models.Q(style_points__gte=0),
                name="stats_style_points_positive",
            ),
        ),
    ]
