# Generated by Django 6.0 on 2026-03-04 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0024_add_profile_customization_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("start_date", models.DateField(db_index=True)),
                ("end_date", models.DateField(db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                ("is_finalized", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "seasons",
                "ordering": ["-start_date"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "is_finalized"], name="season_active_final_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_date__gte", models.F("start_date"))),
                        name="season_date_range_valid",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SeasonReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("rank_min", models.IntegerField()),
                ("rank_max", models.IntegerField()),
                (
                    "reward_type",
                    models.CharField(
                        choices=[
                            ("title", "칭호"),
                            ("border", "프로필 테두리"),
                            ("points", "포인트"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reward_value", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rewards",
                        to="accounts.season",
                    ),
                ),
            ],
            options={
                "db_table": "season_rewards",
                "ordering": ["rank_min", "id"],
            },
        ),
        migrations.CreateModel(
            name="SeasonStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("rating", models.IntegerField(default=1200)),
                ("peak_rating", models.IntegerField(default=1200)),
                ("games_played", models.IntegerField(default=0)),
                ("wins", models.IntegerField(default=0)),
                ("losses", models.IntegerField(default=0)),
                ("draws", models.IntegerField(default=0)),
                ("final_rank", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="accounts.season",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="season_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "season_stats",
            },
        ),
        migrations.CreateModel(
            name="UserSeasonReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_rewards",
                        to="accounts.seasonreward",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_rewards",
                        to="accounts.season",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="season_reward_claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_season_rewards",
            },
        ),
        migrations.AddIndex(
            model_name="seasonreward",
            index=models.Index(
                fields=["season", "rank_min", "rank_max"], name="season_reward_rank_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="seasonreward",
            constraint=models.CheckConstraint(
                condition=models.Q(("rank_min__gte", 1), ("rank_max__gte", models.F("rank_min"))),
                name="season_reward_rank_range_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="seasonstat",
            index=models.Index(fields=["season", "-rating"], name="season_rating_idx"),
        ),
        migrations.AddIndex(
            model_name="seasonstat",
            index=models.Index(fields=["season", "final_rank"], name="season_rank_idx"),
        ),
        migrations.AddIndex(
            model_name="seasonstat",
            index=models.Index(fields=["season", "games_played"], name="season_games_idx"),
        ),
        migrations.AddConstraint(
            model_name="seasonstat",
            constraint=models.CheckConstraint(
                condition=models.Q(("rating__gte", 0), ("rating__lte", 4000)),
                name="season_stats_rating_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="seasonstat",
            constraint=models.CheckConstraint(
                condition=models.Q(("games_played__gte", 0)), name="season_stats_games_nonnegative"
            ),
        ),
        migrations.AddConstraint(
            model_name="seasonstat",
            constraint=models.CheckConstraint(
                condition=models.Q(("wins__gte", 0), ("losses__gte", 0), ("draws__gte", 0)),
                name="season_stats_result_nonnegative",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="seasonstat",
            unique_together={("season", "user")},
        ),
        migrations.AddIndex(
            model_name="userseasonreward",
            index=models.Index(
                fields=["user", "season", "claimed_at"], name="user_season_claim_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userseasonreward",
            unique_together={("user", "reward")},
        ),
    ]
