# Generated by Django 6.0 on 2026-03-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0025_season_seasonreward_seasonstat_userseasonreward_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="season",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("is_active",),
                name="season_single_active_true",
            ),
        ),
    ]
