# Generated by Django 6.0 on 2026-03-05 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_skin_defaults(apps, schema_editor):
    Skin = apps.get_model("accounts", "Skin")
    UserStats = apps.get_model("accounts", "UserStats")

    skins = [
        {
            "name": "클래식",
            "skin_type": "board",
            "price": 0,
            "css_class": "skin-board-classic",
            "description": "기본 체스보드",
            "is_default": True,
            "sort_order": 0,
        },
        {
            "name": "우드",
            "skin_type": "board",
            "price": 200,
            "css_class": "skin-board-wood",
            "description": "따뜻한 우드 톤",
            "is_default": False,
            "sort_order": 10,
        },
        {
            "name": "다크",
            "skin_type": "board",
            "price": 200,
            "css_class": "skin-board-dark",
            "description": "차분한 다크 톤",
            "is_default": False,
            "sort_order": 20,
        },
        {
            "name": "네온",
            "skin_type": "board",
            "price": 500,
            "css_class": "skin-board-neon",
            "description": "강한 대비의 네온 톤",
            "is_default": False,
            "sort_order": 30,
        },
        {
            "name": "대리석",
            "skin_type": "board",
            "price": 500,
            "css_class": "skin-board-marble",
            "description": "밝은 대리석 질감",
            "is_default": False,
            "sort_order": 40,
        },
        {
            "name": "클래식",
            "skin_type": "pieces",
            "price": 0,
            "css_class": "skin-piece-classic",
            "description": "기본 기물",
            "is_default": True,
            "sort_order": 0,
        },
        {
            "name": "픽셀",
            "skin_type": "pieces",
            "price": 300,
            "css_class": "skin-piece-pixel",
            "description": "8비트 레트로 스타일",
            "is_default": False,
            "sort_order": 10,
        },
        {
            "name": "모던",
            "skin_type": "pieces",
            "price": 300,
            "css_class": "skin-piece-modern",
            "description": "간결한 모던 스타일",
            "is_default": False,
            "sort_order": 20,
        },
        {
            "name": "3D",
            "skin_type": "pieces",
            "price": 800,
            "css_class": "skin-piece-3d",
            "description": "입체 음영 스타일",
            "is_default": False,
            "sort_order": 30,
        },
    ]

    for row in skins:
        Skin.objects.update_or_create(
            skin_type=row["skin_type"],
            css_class=row["css_class"],
            defaults=row,
        )

    board_default = Skin.objects.filter(skin_type="board", is_default=True).first()
    piece_default = Skin.objects.filter(skin_type="pieces", is_default=True).first()
    if board_default and piece_default:
        UserStats.objects.filter(selected_board_skin__isnull=True).update(selected_board_skin_id=board_default.id)
        UserStats.objects.filter(selected_piece_skin__isnull=True).update(selected_piece_skin_id=piece_default.id)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0026_season_season_single_active_true"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "skin_type",
                    models.CharField(
                        choices=[("board", "보드"), ("pieces", "기물")], max_length=10
                    ),
                ),
                ("price", models.IntegerField(default=0)),
                ("css_class", models.CharField(max_length=50)),
                ("preview_image", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "skins",
                "ordering": ["skin_type", "sort_order", "price", "id"],
                "indexes": [
                    models.Index(
                        fields=["skin_type", "is_active", "sort_order"], name="skin_type_active_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("price__gte", 0)), name="skin_price_non_negative"
                    ),
                    models.UniqueConstraint(
                        fields=("skin_type", "css_class"), name="skin_type_css_unique"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="userstats",
            name="selected_board_skin",
            field=models.ForeignKey(
                blank=True,
                help_text="선택된 보드 스킨",
                limit_choices_to={"skin_type": "board"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="accounts.skin",
            ),
        ),
        migrations.AddField(
            model_name="userstats",
            name="selected_piece_skin",
            field=models.ForeignKey(
                blank=True,
                help_text="선택된 기물 스킨",
                limit_choices_to={"skin_type": "pieces"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="accounts.skin",
            ),
        ),
        migrations.CreateModel(
            name="SkinPointLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("amount", models.IntegerField()),
                ("balance", models.IntegerField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("game_win", "게임 승리"),
                            ("game_loss", "게임 패배"),
                            ("game_draw", "게임 무승부"),
                            ("skin_purchase", "스킨 구매"),
                            ("puzzle_solve", "퍼즐 클리어"),
                            ("season_reward", "시즌 보상"),
                            ("adjust", "운영자 조정"),
                        ],
                        max_length=50,
                    ),
                ),
                ("reference_id", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skin_point_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "skin_point_logs",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["user", "-created_at"], name="skin_point_user_recent_idx"),
                    models.Index(
                        fields=["reason", "-created_at"], name="skin_point_reason_recent_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserSkin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("acquired_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acquired_method",
                    models.CharField(
                        choices=[("purchase", "구매"), ("reward", "보상"), ("system", "기본 제공")],
                        default="purchase",
                        max_length=20,
                    ),
                ),
                (
                    "skin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owners",
                        to="accounts.skin",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_skins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_skins",
                "indexes": [
                    models.Index(fields=["user", "-acquired_at"], name="user_skin_recent_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("user", "skin"), name="user_skin_unique")
                ],
            },
        ),
        migrations.RunPython(seed_skin_defaults, migrations.RunPython.noop),
    ]
