# Generated by Django 6.0 on 2026-03-07

from django.db import migrations


def add_extra_skins(apps, schema_editor):
    Skin = apps.get_model("accounts", "Skin")

    rows = [
        {
            "name": "옵시디언",
            "skin_type": "board",
            "price": 700,
            "css_class": "skin-board-obsidian",
            "description": "차가운 흑요석 질감 보드",
            "is_default": False,
            "is_active": True,
            "sort_order": 50,
        },
        {
            "name": "사쿠라",
            "skin_type": "board",
            "price": 700,
            "css_class": "skin-board-sakura",
            "description": "벚꽃 톤의 파스텔 보드",
            "is_default": False,
            "is_active": True,
            "sort_order": 60,
        },
        {
            "name": "글래스",
            "skin_type": "pieces",
            "price": 900,
            "css_class": "skin-piece-glass",
            "description": "유리 재질 느낌의 투명 기물",
            "is_default": False,
            "is_active": True,
            "sort_order": 40,
        },
        {
            "name": "룬",
            "skin_type": "pieces",
            "price": 900,
            "css_class": "skin-piece-rune",
            "description": "고대 문양 느낌의 기물 스타일",
            "is_default": False,
            "is_active": True,
            "sort_order": 50,
        },
    ]

    for row in rows:
        Skin.objects.update_or_create(
            skin_type=row["skin_type"],
            css_class=row["css_class"],
            defaults=row,
        )


def remove_extra_skins(apps, schema_editor):
    Skin = apps.get_model("accounts", "Skin")
    css_classes = [
        "skin-board-obsidian",
        "skin-board-sakura",
        "skin-piece-glass",
        "skin-piece-rune",
    ]
    Skin.objects.filter(css_class__in=css_classes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0028_userstats_owned_customization"),
    ]

    operations = [
        migrations.RunPython(add_extra_skins, remove_extra_skins),
    ]
