# Generated by Django 6.0 on 2026-03-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0029_add_extra_skins"),
    ]

    operations = [
        migrations.AddField(
            model_name="userstats",
            name="owned_profile_card_frames",
            field=models.JSONField(
                blank=True, default=list, help_text="시즌 보상으로 획득한 프로필 카드 프레임 목록"
            ),
        ),
        migrations.AddField(
            model_name="userstats",
            name="owned_season_titles",
            field=models.JSONField(
                blank=True, default=list, help_text="시즌 보상으로 획득한 칭호 목록"
            ),
        ),
        migrations.AddField(
            model_name="userstats",
            name="profile_card_frame",
            field=models.CharField(
                blank=True, default="", help_text="선택된 프로필 카드 프레임 키", max_length=40
            ),
        ),
        migrations.AddField(
            model_name="userstats",
            name="season_title",
            field=models.CharField(
                blank=True, default="", help_text="활성 시즌 칭호", max_length=80
            ),
        ),
    ]
