# Generated by Django 6.0 on 2026-03-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0030_userstats_owned_profile_card_frames_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seasonreward",
            name="reward_type",
            field=models.CharField(
                choices=[("title", "칭호"), ("border", "프로필 카드 프레임"), ("points", "포인트")],
                max_length=20,
            ),
        ),
    ]
