from django.urls import path

from apps.community.views import (
    BoardCategoryListView,
    BoardCommentCreateView,
    BoardCommentDetailView,
    BoardCommentLikeToggleView,
    BoardDetailView,
    BoardListCreateView,
    BoardReportCreateView,
    CurrentGuildView,
    GuildAvatarUpdateView,
    GuildChatView,
    GuildDetailView,
    GuildJoinRequestReviewView,
    GuildJoinRequestView,
    GuildLeaveView,
    GuildListCreateView,
    GuildMemberKickView,
    GuildMemberRoleUpdateView,
    GuildNoticeListCreateView,
    GuildTransferLeaderView,
    MyActivePartyView,
    PartyChatView,
    PartyCloseView,
    PartyDetailView,
    PartyInviteListView,
    PartyInviteRespondView,
    PartyInviteView,
    PartyKickView,
    PartyLeaveView,
    PartyLineupLockView,
    PartyListCreateView,
    PartyReadyView,
    PartySlotView,
    PartyTransferLeaderView,
    TeamBattleJoinView,
    TeamBattleListCreateView,
    TeamBattleRoundResultView,
    TeamBattleStartView,
    TournamentListCreateView,
    TournamentRegisterView,
    TournamentUnregisterView,
)

app_name = "community"

urlpatterns = [
    path("guilds/", GuildListCreateView.as_view(), name="guild-list"),
    path("guilds/me/current/", CurrentGuildView.as_view(), name="guild-current"),
    path("guilds/<int:guild_id>/", GuildDetailView.as_view(), name="guild-detail"),
    path("guilds/<int:guild_id>/join/", GuildJoinRequestView.as_view(), name="guild-join"),
    path(
        "guilds/requests/<int:request_id>/review/",
        GuildJoinRequestReviewView.as_view(),
        name="guild-join-review",
    ),
    path("guilds/<int:guild_id>/leave/", GuildLeaveView.as_view(), name="guild-leave"),
    path(
        "guilds/<int:guild_id>/notice/",
        GuildNoticeListCreateView.as_view(),
        name="guild-notice",
    ),
    path("guilds/<int:guild_id>/avatar/", GuildAvatarUpdateView.as_view(), name="guild-avatar"),
    path(
        "guilds/<int:guild_id>/members/<int:user_id>/role/",
        GuildMemberRoleUpdateView.as_view(),
        name="guild-member-role",
    ),
    path(
        "guilds/<int:guild_id>/members/<int:user_id>/kick/",
        GuildMemberKickView.as_view(),
        name="guild-member-kick",
    ),
    path(
        "guilds/<int:guild_id>/transfer/<int:user_id>/",
        GuildTransferLeaderView.as_view(),
        name="guild-transfer",
    ),
    path("guilds/<int:guild_id>/chat/", GuildChatView.as_view(), name="guild-chat"),
    path("parties/", PartyListCreateView.as_view(), name="party-list"),
    path("parties/me/active/", MyActivePartyView.as_view(), name="party-active"),
    path("parties/<int:party_id>/", PartyDetailView.as_view(), name="party-detail"),
    path("parties/invites/", PartyInviteListView.as_view(), name="party-invite-list"),
    path("parties/<int:party_id>/invite/", PartyInviteView.as_view(), name="party-invite"),
    path(
        "parties/invites/<int:invite_id>/respond/",
        PartyInviteRespondView.as_view(),
        name="party-invite-respond",
    ),
    path("parties/<int:party_id>/leave/", PartyLeaveView.as_view(), name="party-leave"),
    path("parties/<int:party_id>/close/", PartyCloseView.as_view(), name="party-close"),
    path(
        "parties/<int:party_id>/transfer/<int:user_id>/",
        PartyTransferLeaderView.as_view(),
        name="party-transfer",
    ),
    path(
        "parties/<int:party_id>/members/<int:user_id>/kick/",
        PartyKickView.as_view(),
        name="party-kick",
    ),
    path("parties/<int:party_id>/ready/", PartyReadyView.as_view(), name="party-ready"),
    path("parties/<int:party_id>/slot/", PartySlotView.as_view(), name="party-slot"),
    path("parties/<int:party_id>/lineup/", PartyLineupLockView.as_view(), name="party-lineup"),
    path("parties/<int:party_id>/chat/", PartyChatView.as_view(), name="party-chat"),
    path("boards/categories/", BoardCategoryListView.as_view(), name="board-categories"),
    path("boards/posts/", BoardListCreateView.as_view(), name="board-posts"),
    path("boards/posts/<int:post_id>/", BoardDetailView.as_view(), name="board-detail"),
    path(
        "boards/posts/<int:post_id>/comments/",
        BoardCommentCreateView.as_view(),
        name="board-comment-create",
    ),
    path(
        "boards/comments/<int:comment_id>/like/",
        BoardCommentLikeToggleView.as_view(),
        name="board-comment-like",
    ),
    path(
        "boards/comments/<int:comment_id>/",
        BoardCommentDetailView.as_view(),
        name="board-comment-detail",
    ),
    path("boards/reports/", BoardReportCreateView.as_view(), name="board-report"),
    path("tournaments/", TournamentListCreateView.as_view(), name="tournament-list"),
    path(
        "tournaments/<int:tournament_id>/register/",
        TournamentRegisterView.as_view(),
        name="tournament-register",
    ),
    path(
        "tournaments/<int:tournament_id>/unregister/",
        TournamentUnregisterView.as_view(),
        name="tournament-unregister",
    ),
    path("team-battles/", TeamBattleListCreateView.as_view(), name="team-battles"),
    path(
        "team-battles/<int:match_id>/join/", TeamBattleJoinView.as_view(), name="team-battle-join"
    ),
    path(
        "team-battles/<int:match_id>/start/",
        TeamBattleStartView.as_view(),
        name="team-battle-start",
    ),
    path(
        "team-battles/<int:match_id>/rounds/<int:round_id>/result/",
        TeamBattleRoundResultView.as_view(),
        name="team-battle-round-result",
    ),
]
