# Generated by Django 6.0 on 2025-12-27 16:26

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(db_index=True, max_length=100, null=True, unique=True)),
                ('nickname', models.CharField(help_text='게임 내 표시 이름', max_length=50, unique=True)),
                ('password', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('rating', models.IntegerField(default=1200, help_text='ELO 레이팅 시스템')),
                ('games_played', models.IntegerField(default=0, help_text='총 게임 수')),
                ('games_won', models.IntegerField(default=0, help_text='승리 수')),
                ('games_lost', models.IntegerField(default=0, help_text='패배 수')),
                ('games_draw', models.IntegerField(default=0, help_text='무승부 수')),
                ('avatar_url', models.URLField(blank=True, help_text='S3 프로필 사진 URL', max_length=500, null=True)),
                ('bio', models.TextField(blank=True, help_text='자기소개')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
                'db_table': 'users',
                'ordering': ['-rating', '-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SocialUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('github', 'GitHub'), ('kakao', 'Kakao'), ('naver', 'Naver')], help_text='OAuth 제공자', max_length=20)),
                ('provider_user_id', models.CharField(help_text='제공자의 사용자 ID', max_length=255)),
                ('access_token', models.TextField(blank=True, help_text='OAuth Access Token')),
                ('refresh_token', models.TextField(blank=True, help_text='OAuth Refresh Token')),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='토큰 만료 시간', null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='추가 데이터 (이메일, 프로필 등)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='연결된 사용자', on_delete=django.db.models.deletion.CASCADE, related_name='social_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '소셜 계정',
                'verbose_name_plural': '소셜 계정',
                'db_table': 'social_users',
                'indexes': [models.Index(fields=['user', 'provider'], name='social_user_user_id_0c7452_idx'), models.Index(fields=['provider', 'provider_user_id'], name='social_user_provide_59cef3_idx')],
                'unique_together': {('provider', 'provider_user_id')},
            },
        ),
    ]
