# Generated by Django 6.0 on 2026-01-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chess", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="increment_seconds",
            field=models.IntegerField(default=10, help_text="턴 종료 시 추가 시간 (초)"),
        ),
        migrations.AlterField(
            model_name="room",
            name="time_limit",
            field=models.IntegerField(default=15, help_text="각 플레이어당 시간 제한 (분)"),
        ),
        migrations.AddField(
            model_name="game",
            name="turn_started_at",
            field=models.DateTimeField(blank=True, help_text="현재 턴 시작 시간", null=True),
        ),
        migrations.AddConstraint(
            model_name="room",
            constraint=models.CheckConstraint(
                condition=models.Q(increment_seconds__gte=0),
                name="increment_seconds_nonnegative",
            ),
        ),
    ]
