# Generated by Django 6.0 on 2026-01-16 17:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chess", "0002_room_increment_game_turn_started"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="move",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="room",
            name="password",
            field=models.CharField(blank=True, help_text="방 비밀번호", max_length=128),
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.CheckConstraint(
                condition=models.Q(("white_time_remaining__gte", 0)), name="white_time_nonnegative"
            ),
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.CheckConstraint(
                condition=models.Q(("black_time_remaining__gte", 0)), name="black_time_nonnegative"
            ),
        ),
        migrations.AddConstraint(
            model_name="move",
            constraint=models.UniqueConstraint(
                fields=("game", "move_number", "player_color"), name="unique_move_per_turn"
            ),
        ),
        migrations.AddConstraint(
            model_name="move",
            constraint=models.CheckConstraint(
                condition=models.Q(("move_number__gte", 1)), name="move_number_positive"
            ),
        ),
    ]
