# Generated by Django 6.0 on 2026-01-17 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chess", "0003_alter_move_unique_together_alter_room_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="room",
            field=models.ForeignKey(
                help_text="게임이 진행되는 방",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games",
                to="chess.room",
            ),
        ),
    ]
