# Generated by Django 6.0 on 2026-02-10 09:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chess", "0009_allow_zero_time_limit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="move",
            name="captured_color",
            field=models.CharField(
                blank=True,
                choices=[("white", "백"), ("black", "흑")],
                help_text="잡은 기물의 색상",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="move",
            name="captured_piece",
            field=models.CharField(
                blank=True,
                choices=[
                    ("P", "Pawn"),
                    ("N", "Knight"),
                    ("B", "Bishop"),
                    ("R", "Rook"),
                    ("Q", "Queen"),
                ],
                help_text="잡은 기물 (빈 값이면 잡은 기물 없음)",
                max_length=1,
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["result", "-created_at"], name="games_result_fb360a_idx"),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["room", "result"], name="games_room_id_f751a5_idx"),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["white_player", "-created_at"], name="games_white_p_60c24e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["black_player", "-created_at"], name="games_black_p_a6dac5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["white_player", "black_player", "result"], name="games_white_p_64fe18_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="move",
            index=models.Index(fields=["game", "is_capture"], name="moves_game_id_757cea_idx"),
        ),
    ]
