# Generated by Django 6.0 on 2026-02-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chess", "0010_add_captured_piece_and_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiDifficultySetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("easy", "쉬움"), ("medium", "중간"), ("hard", "어려움")],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("depth", models.IntegerField(default=0)),
                ("randomness", models.IntegerField(default=4)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI 난이도 설정",
                "verbose_name_plural": "AI 난이도 설정",
                "db_table": "ai_difficulty_settings",
            },
        ),
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("quick", "빠른 대전"),
                    ("custom", "사용자 방"),
                    ("ai_easy", "AI 대전(쉬움)"),
                    ("ai_medium", "AI 대전(중간)"),
                    ("ai_hard", "AI 대전(어려움)"),
                ],
                default="custom",
                help_text="빠른 대전 또는 사용자 방",
                max_length=10,
            ),
        ),
    ]
