# Generated by Django 6.0 on 2026-02-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chess", "0011_aidifficultysetting_alter_room_room_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="aidifficultysetting",
            name="delay_ms",
            field=models.IntegerField(default=800),
        ),
    ]
