# Generated by Django 6.0 on 2026-02-12 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chess", "0012_aidifficultysetting_delay_ms"),
        ("chess", "0012_alter_room_room_type"),
    ]

    operations = []
