# Generated by Django 6.0 on 2026-02-17 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chess", "0013_merge_20260212_1536"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameInvite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("accepted", "수락"),
                            ("declined", "거절"),
                            ("expired", "만료"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("time_limit", models.IntegerField(default=10, help_text="게임 시간 제한 (분)")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "from_user",
                    models.ForeignKey(
                        help_text="초대를 보낸 사용자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        help_text="수락 시 생성된 방",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invites",
                        to="chess.room",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        help_text="초대를 받은 사용자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "game_invites",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["to_user", "status", "-created_at"],
                        name="game_invite_to_user_219049_idx",
                    ),
                    models.Index(
                        fields=["from_user", "-created_at"], name="game_invite_from_us_3c8b60_idx"
                    ),
                ],
            },
        ),
    ]
