# Generated by Django 6.0 on 2026-02-26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chess", "0014_add_game_invite_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LobbyMessageReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emoji", models.CharField(max_length=8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="chess.lobbymessage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lobby_message_reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "lobby_message_reactions",
                "verbose_name": "로비 메시지 반응",
                "verbose_name_plural": "로비 메시지 반응",
                "indexes": [
                    models.Index(
                        fields=["message", "emoji"],
                        name="lobby_react_msg_emoji_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="lobby_react_user_created_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("message", "user", "emoji"),
                        name="uniq_lobby_message_reaction",
                    )
                ],
            },
        ),
    ]

