# Generated by Django 6.0 on 2026-03-01 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chess", "0015_add_lobby_message_reaction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Puzzle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "lichess_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=16, null=True, unique=True
                    ),
                ),
                ("fen", models.CharField(max_length=120)),
                ("moves", models.JSONField(default=list)),
                ("rating", models.IntegerField(db_index=True, default=1500)),
                ("themes", models.JSONField(default=list)),
                ("game_url", models.URLField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "puzzles",
                "ordering": ["-rating", "-id"],
                "indexes": [models.Index(fields=["rating", "id"], name="puzzle_rating_idx")],
            },
        ),
        migrations.CreateModel(
            name="DailyPuzzle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "puzzle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_usages",
                        to="chess.puzzle",
                    ),
                ),
            ],
            options={
                "db_table": "daily_puzzles",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="UserPuzzleAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("solved", models.BooleanField(default=False)),
                ("attempts", models.IntegerField(default=0)),
                ("hints_used", models.IntegerField(default=0)),
                ("moves_made", models.JSONField(default=list)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("solved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "daily_puzzle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_attempts",
                        to="chess.dailypuzzle",
                    ),
                ),
                (
                    "puzzle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_attempts",
                        to="chess.puzzle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "user_puzzle_attempts",
                "indexes": [
                    models.Index(
                        fields=["user", "solved", "solved_at"], name="puzzle_user_solved_idx"
                    ),
                    models.Index(fields=["daily_puzzle", "user"], name="puzzle_daily_user_idx"),
                ],
                "unique_together": {("user", "daily_puzzle")},
            },
        ),
    ]
