# Generated by Django 6.0 on 2026-03-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chess", "0016_puzzle_dailypuzzle_userpuzzleattempt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailypuzzle",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AddField(
            model_name="dailypuzzle",
            name="level",
            field=models.CharField(
                choices=[("easy", "쉬움"), ("medium", "중간"), ("hard", "어려움")],
                db_index=True,
                default="medium",
                max_length=12,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailypuzzle",
            unique_together={("date", "level")},
        ),
        migrations.AddIndex(
            model_name="dailypuzzle",
            index=models.Index(
                fields=["date", "level"], name="daily_puzzle_date_level_idx"
            ),
        ),
    ]
