# Generated by Django 6.0 on 2025-12-27 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('quick', '빠른 대전'), ('custom', '사용자 방')], default='custom', help_text='빠른 대전 또는 사용자 방', max_length=10)),
                ('title', models.CharField(blank=True, help_text='사용자 방 제목', max_length=100)),
                ('status', models.CharField(choices=[('waiting', '대기 중'), ('playing', '게임 중'), ('finished', '종료')], default='waiting', help_text='방 상태', max_length=20)),
                ('is_private', models.BooleanField(default=False, help_text='비공개방 여부')),
                ('password', models.CharField(blank=True, help_text='방 비밀번호', max_length=50)),
                ('allow_spectators', models.BooleanField(default=True, help_text='관전 허용 여부')),
                ('time_limit', models.IntegerField(default=30, help_text='각 플레이어당 시간 제한 (분)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('guest', models.ForeignKey(blank=True, help_text='참가한 사용자', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joined_rooms', to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(help_text='방을 만든 사용자', on_delete=django.db.models.deletion.CASCADE, related_name='hosted_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '방',
                'verbose_name_plural': '방',
                'db_table': 'rooms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fen', models.CharField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', help_text='FEN 표기법으로 저장된 현재 보드 상태', max_length=100)),
                ('pgn', models.TextField(blank=True, help_text='PGN(Portable Game Notation) 형식의 게임 기록')),
                ('result', models.CharField(choices=[('playing', '진행 중'), ('white_win', '백 승리'), ('black_win', '흑 승리'), ('draw', '무승부'), ('stalemate', '스테일메이트'), ('checkmate_white', '체크메이트 - 백 승리'), ('checkmate_black', '체크메이트 - 흑 승리'), ('timeout_white', '시간 초과 - 흑 승리'), ('timeout_black', '시간 초과 - 백 승리'), ('resignation_white', '기권 - 흑 승리'), ('resignation_black', '기권 - 백 승리'), ('draw_agreement', '합의 무승부'), ('draw_repetition', '3회 반복 무승부'), ('draw_fifty_move', '50수 규칙 무승부'), ('draw_insufficient', '기물 부족 무승부')], default='playing', help_text='게임 결과', max_length=20)),
                ('move_count', models.IntegerField(default=0, help_text='총 착수 횟수')),
                ('white_time_remaining', models.IntegerField(help_text='백 플레이어 남은 시간 (초)')),
                ('black_time_remaining', models.IntegerField(help_text='흑 플레이어 남은 시간 (초)')),
                ('current_turn', models.CharField(choices=[('white', '백'), ('black', '흑')], default='white', help_text='현재 차례 플레이어', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('black_player', models.ForeignKey(help_text='흑(Black) 플레이어', on_delete=django.db.models.deletion.CASCADE, related_name='games_as_black', to=settings.AUTH_USER_MODEL)),
                ('white_player', models.ForeignKey(help_text='백(White) 플레이어', on_delete=django.db.models.deletion.CASCADE, related_name='games_as_white', to=settings.AUTH_USER_MODEL)),
                ('room', models.OneToOneField(help_text='게임이 진행되는 방', on_delete=django.db.models.deletion.CASCADE, related_name='game', to='chess.room')),
            ],
            options={
                'verbose_name': '게임',
                'verbose_name_plural': '게임',
                'db_table': 'games',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_number', models.IntegerField(help_text='착수 번호 (1부터 시작)')),
                ('player_color', models.CharField(choices=[('white', '백'), ('black', '흑')], help_text='착수한 플레이어의 색상', max_length=5)),
                ('piece', models.CharField(choices=[('P', 'Pawn (폰)'), ('N', 'Knight (나이트)'), ('B', 'Bishop (비숍)'), ('R', 'Rook (룩)'), ('Q', 'Queen (퀸)'), ('K', 'King (킹)')], help_text='이동한 체스 기물', max_length=1)),
                ('from_square', models.CharField(help_text='출발 위치 (예: e2, a1)', max_length=2)),
                ('to_square', models.CharField(help_text='도착 위치 (예: e4, h8)', max_length=2)),
                ('san', models.CharField(help_text='Standard Algebraic Notation', max_length=10)),
                ('uci', models.CharField(help_text='Universal Chess Interface notation', max_length=5)),
                ('is_capture', models.BooleanField(default=False, help_text='기물을 잡았는지 여부')),
                ('is_check', models.BooleanField(default=False, help_text='체크 상태인지 여부')),
                ('is_checkmate', models.BooleanField(default=False, help_text='체크메이트 상태인지 여부')),
                ('is_castling', models.BooleanField(default=False, help_text='캐슬링 착수인지 여부')),
                ('is_en_passant', models.BooleanField(default=False, help_text='앙파상 착수인지 여부')),
                ('promotion', models.CharField(blank=True, choices=[('Q', 'Queen'), ('R', 'Rook'), ('B', 'Bishop'), ('N', 'Knight')], help_text='폰 승진 시 선택한 기물', max_length=1)),
                ('fen_after_move', models.CharField(help_text='착수 후 보드 상태 (FEN)', max_length=100)),
                ('time_spent', models.FloatField(blank=True, help_text='이번 착수에 소요된 시간 (초)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(help_text='착수가 속한 게임', on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='chess.game')),
            ],
            options={
                'verbose_name': '착수',
                'verbose_name_plural': '착수',
                'db_table': 'moves',
                'ordering': ['game', 'move_number', 'player_color'],
                'indexes': [models.Index(fields=['game', 'move_number'], name='moves_game_id_325edd_idx'), models.Index(fields=['game', 'created_at'], name='moves_game_id_d4d651_idx')],
                'unique_together': {('game', 'move_number', 'player_color')},
            },
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['status', 'room_type'], name='rooms_status_75ed3e_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['host'], name='rooms_host_id_4baddc_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['result'], name='games_result_34a4e4_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['white_player', 'black_player'], name='games_white_p_1742a4_idx'),
        ),
    ]
