# Generated by Django 6.0 on 2026-04-07 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=24, unique=True)),
                ("title", models.CharField(max_length=40)),
                ("description", models.CharField(blank=True, default="", max_length=120)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_enabled", models.BooleanField(default=True)),
                ("is_recruitment", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "board_categories",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="BoardPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("content", models.TextField()),
                ("is_pinned", models.BooleanField(default=False)),
                ("is_blinded", models.BooleanField(default=False)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("comment_count", models.PositiveIntegerField(default=0)),
                ("last_commented_at", models.DateTimeField(blank=True, null=True)),
                ("guild_name", models.CharField(blank=True, default="", max_length=40)),
                ("recruitment_slots", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("minimum_rating", models.PositiveIntegerField(blank=True, null=True)),
                ("active_time_band", models.CharField(blank=True, default="", max_length=80)),
                ("join_policy_text", models.CharField(blank=True, default="", max_length=40)),
                ("contact_method", models.CharField(blank=True, default="", max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="board_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posts",
                        to="community.boardcategory",
                    ),
                ),
            ],
            options={
                "db_table": "board_posts",
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BoardComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("content", models.CharField(max_length=500)),
                ("is_blinded", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="board_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="community.boardpost",
                    ),
                ),
            ],
            options={
                "db_table": "board_comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="BoardReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[("post", "게시글"), ("comment", "댓글")], max_length=16
                    ),
                ),
                ("reason", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "대기"), ("resolved", "처리")],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="community.boardcomment",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="community.boardpost",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="board_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "board_reports",
            },
        ),
        migrations.CreateModel(
            name="Guild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=40, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=48, unique=True)),
                ("description", models.TextField(blank=True)),
                ("notice", models.CharField(blank=True, default="", max_length=200)),
                (
                    "join_policy",
                    models.CharField(
                        choices=[("open", "자유 가입"), ("approval", "승인제")],
                        default="approval",
                        max_length=16,
                    ),
                ),
                ("min_rating", models.IntegerField(default=0)),
                ("active_hours", models.CharField(blank=True, default="", max_length=80)),
                ("contact_channel", models.CharField(blank=True, default="", max_length=80)),
                ("team_rating", models.IntegerField(default=1200)),
                ("member_count", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_guilds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "guilds",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GuildChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("content", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="community.guild",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guild_chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "guild_chat_messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GuildJoinRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "대기"), ("approved", "승인"), ("rejected", "거절")],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("message", models.CharField(blank=True, default="", max_length=200)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_requests",
                        to="community.guild",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_guild_join_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guild_join_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "guild_join_requests",
            },
        ),
        migrations.CreateModel(
            name="GuildMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("leader", "길드장"),
                            ("vice", "부길드장"),
                            ("manager", "운영진"),
                            ("member", "일반"),
                        ],
                        default="member",
                        max_length=16,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="community.guild",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guild_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "guild_members",
            },
        ),
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=60)),
                ("description", models.CharField(blank=True, default="", max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "모집중"),
                            ("ready", "준비완료"),
                            ("queued", "매칭대기"),
                            ("battling", "대전중"),
                            ("closed", "종료"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("max_members", models.PositiveSmallIntegerField(default=3)),
                ("lineup_locked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "leader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="led_parties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "parties",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PartyChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("content", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="community.party",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="party_chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "party_chat_messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PartyInvite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("accepted", "수락"),
                            ("declined", "거절"),
                            ("expired", "만료"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="party_invites_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="community.party",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="party_invites_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "party_invites",
            },
        ),
        migrations.CreateModel(
            name="PartyMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slot", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("is_ready", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="community.party",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="party_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "party_members",
            },
        ),
        migrations.CreateModel(
            name="TeamBattleMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "battle_type",
                    models.CharField(
                        choices=[("party", "단체전"), ("guild", "길드전")], max_length=16
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "대기"),
                            ("live", "진행중"),
                            ("finished", "종료"),
                            ("cancelled", "취소"),
                        ],
                        default="waiting",
                        max_length=16,
                    ),
                ),
                ("host_remaining", models.PositiveSmallIntegerField(default=3)),
                ("guest_remaining", models.PositiveSmallIntegerField(default=3)),
                ("winner_side", models.CharField(blank=True, default="", max_length=16)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guest_guild",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_guild_battles",
                        to="community.guild",
                    ),
                ),
                (
                    "guest_party",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_team_battles",
                        to="community.party",
                    ),
                ),
                (
                    "host_guild",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="host_guild_battles",
                        to="community.guild",
                    ),
                ),
                (
                    "host_party",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="host_team_battles",
                        to="community.party",
                    ),
                ),
            ],
            options={
                "db_table": "team_battle_matches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=80)),
                ("slug", models.SlugField(blank=True, max_length=96, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "준비중"),
                            ("open", "모집중"),
                            ("live", "진행중"),
                            ("finished", "종료"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("max_participants", models.PositiveSmallIntegerField(default=8)),
                ("minimum_rating", models.PositiveIntegerField(default=0)),
                ("maximum_rating", models.PositiveIntegerField(default=4000)),
                ("winner_title", models.CharField(blank=True, default="", max_length=80)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tournaments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tournaments",
                "ordering": ["start_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TournamentEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("seed", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "등록"),
                            ("confirmed", "확정"),
                            ("eliminated", "탈락"),
                        ],
                        default="registered",
                        max_length=16,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="community.tournament",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tournament_entries",
            },
        ),
        migrations.AddIndex(
            model_name="boardpost",
            index=models.Index(
                fields=["category", "-created_at"], name="board_post_cat_created_ix"
            ),
        ),
        migrations.AddIndex(
            model_name="boardpost",
            index=models.Index(
                fields=["category", "-view_count"], name="board_post_category_views_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="boardpost",
            index=models.Index(
                fields=["author", "-created_at"], name="board_post_author_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="boardcomment",
            index=models.Index(
                fields=["post", "created_at"], name="board_comment_post_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="boardreport",
            index=models.Index(
                fields=["status", "-created_at"], name="board_report_stat_created_ix"
            ),
        ),
        migrations.AddIndex(
            model_name="guild",
            index=models.Index(fields=["slug"], name="guild_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="guild",
            index=models.Index(
                fields=["join_policy", "-created_at"], name="guild_policy_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="guild",
            index=models.Index(
                fields=["-team_rating", "-member_count"], name="guild_rating_members_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="guildchatmessage",
            index=models.Index(fields=["guild", "-created_at"], name="guild_chat_created_idx"),
        ),
        migrations.AddIndex(
            model_name="guildjoinrequest",
            index=models.Index(
                fields=["guild", "status", "-created_at"], name="guild_join_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="guildjoinrequest",
            index=models.Index(
                fields=["user", "status", "-created_at"], name="guild_join_user_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="guildjoinrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("guild", "user"),
                name="uniq_pending_guild_join_request",
            ),
        ),
        migrations.AddIndex(
            model_name="guildmember",
            index=models.Index(fields=["guild", "role"], name="guild_member_role_idx"),
        ),
        migrations.AddIndex(
            model_name="guildmember",
            index=models.Index(fields=["user", "-joined_at"], name="guild_member_user_joined_idx"),
        ),
        migrations.AddConstraint(
            model_name="guildmember",
            constraint=models.UniqueConstraint(fields=("guild", "user"), name="uniq_guild_member"),
        ),
        migrations.AddIndex(
            model_name="party",
            index=models.Index(fields=["status", "-updated_at"], name="party_status_updated_idx"),
        ),
        migrations.AddIndex(
            model_name="party",
            index=models.Index(fields=["leader", "-created_at"], name="party_leader_created_idx"),
        ),
        migrations.AddIndex(
            model_name="partychatmessage",
            index=models.Index(fields=["party", "-created_at"], name="party_chat_created_idx"),
        ),
        migrations.AddIndex(
            model_name="partyinvite",
            index=models.Index(
                fields=["to_user", "status", "-created_at"], name="party_invite_to_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partyinvite",
            index=models.Index(
                fields=["party", "status", "-created_at"], name="party_invite_party_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="partyinvite",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("party", "to_user"),
                name="uniq_pending_party_invite",
            ),
        ),
        migrations.AddIndex(
            model_name="partymember",
            index=models.Index(fields=["party", "is_ready"], name="party_member_ready_idx"),
        ),
        migrations.AddIndex(
            model_name="partymember",
            index=models.Index(fields=["user", "-joined_at"], name="party_member_user_joined_idx"),
        ),
        migrations.AddConstraint(
            model_name="partymember",
            constraint=models.UniqueConstraint(fields=("party", "user"), name="uniq_party_member"),
        ),
        migrations.AddConstraint(
            model_name="partymember",
            constraint=models.UniqueConstraint(
                condition=models.Q(("slot__isnull", False)),
                fields=("party", "slot"),
                name="uniq_party_slot",
            ),
        ),
        migrations.AddIndex(
            model_name="teambattlematch",
            index=models.Index(
                fields=["battle_type", "status", "-created_at"], name="team_battle_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tournament",
            index=models.Index(fields=["status", "start_at"], name="tournament_status_start_idx"),
        ),
        migrations.AddIndex(
            model_name="tournamententry",
            index=models.Index(
                fields=["tournament", "status", "seed"], name="tour_entry_status_seed_ix"
            ),
        ),
        migrations.AddConstraint(
            model_name="tournamententry",
            constraint=models.UniqueConstraint(
                fields=("tournament", "user"), name="uniq_tournament_entry"
            ),
        ),
    ]
