# Generated by Django 6.0 on 2026-04-07 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chess", "0017_dailypuzzle_level_split"),
        ("community", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamBattleParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("host", "호스트"), ("guest", "게스트")], max_length=16
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                ("wins", models.PositiveSmallIntegerField(default=0)),
                ("is_eliminated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="community.teambattlematch",
                    ),
                ),
                (
                    "source_guild",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="community.guild",
                    ),
                ),
                (
                    "source_party",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="community.party",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_battle_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "team_battle_participants",
                "ordering": ["side", "order"],
            },
        ),
        migrations.CreateModel(
            name="TeamBattleRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("round_number", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "대기"), ("live", "진행중"), ("finished", "종료")],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[("host", "호스트 승"), ("guest", "게스트 승"), ("draw", "무승부")],
                        default="",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team_battle_rounds",
                        to="chess.game",
                    ),
                ),
                (
                    "guest_participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_rounds",
                        to="community.teambattleparticipant",
                    ),
                ),
                (
                    "host_participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="host_rounds",
                        to="community.teambattleparticipant",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="community.teambattlematch",
                    ),
                ),
            ],
            options={
                "db_table": "team_battle_rounds",
                "ordering": ["round_number"],
            },
        ),
        migrations.CreateModel(
            name="GuildAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("action", models.CharField(max_length=32)),
                ("detail", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guild_audit_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="community.guild",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guild_audit_targets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "guild_audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["guild", "-created_at"], name="guild_audit_created_idx"),
                    models.Index(fields=["action", "-created_at"], name="guild_audit_action_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="teambattleparticipant",
            index=models.Index(
                fields=["match", "side", "is_eliminated"], name="team_battle_side_alive_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="teambattleparticipant",
            constraint=models.UniqueConstraint(
                fields=("match", "side", "order"), name="uniq_team_battle_lineup_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="teambattleparticipant",
            constraint=models.UniqueConstraint(
                fields=("match", "user"), name="uniq_team_battle_user"
            ),
        ),
        migrations.AddIndex(
            model_name="teambattleround",
            index=models.Index(
                fields=["match", "status", "round_number"], name="team_battle_round_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="teambattleround",
            constraint=models.UniqueConstraint(
                fields=("match", "round_number"), name="uniq_team_battle_round"
            ),
        ),
    ]
