# Generated by Django 6.0 on 2026-02-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("friend_request", "친구 요청"),
                    ("friend_accept", "친구 수락"),
                    ("match_found", "매칭 완료"),
                    ("room_event", "방 이벤트"),
                    ("rematch", "리매치"),
                    ("game_result", "게임 결과"),
                    ("rating_change", "레이팅 변동"),
                    ("tier_promotion", "티어 승격"),
                    ("direct_message", "1:1 메시지"),
                    ("admin_notice", "공지"),
                ],
                max_length=30,
            ),
        ),
    ]
